import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]

# Cursor
[cursor]
blink_interval = 500

[cursor.style]
shape = "Underline"
blinking = "On"

# Environment config
[env]
TERM = "xterm-256color"

# Font config
[font]
size = 14.0
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
bold = { family = "FiraCode Nerd Font Mono", style = "SemiBold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Light" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Medium" }

# Window config
[window]
dimensions = {columns = 125, lines = 35}
padding = {x = 5, y = 10}
dynamic_padding = true
dynamic_title = true
decorations = "Buttonless"
