# Colors (One Half Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'

# Normal colors
[colors.normal]
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'

# Bright colors (same as normal colors)
[colors.bright]
black = '#5d677a'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'
