#!/bin/zsh

# Make a brew dump file
echo "\n# Brewfile"
brew bundle dump --force --file=$BACKUP_HOME/brew/Brewfile
echo "Dumped file to $BACKUP_HOME/brew/Brewfile"

# Exporting dock layout
echo "\n# Dock layout"
echo "Exporting dock layout to $BACKUP_HOME/dock/dock-layout.plist"
defaults export com.apple.dock $BACKUP_HOME/dock/dock-layout.plist
