#!/bin/zsh

# Exporting dock layout (macOS only)
if (( $+commands[defaults] )); then
    echo "# Exporting dock layout to /tmp/dock-layout.plist"
    defaults export com.apple.dock /tmp/dock-layout.plist
fi

# Antidote
echo "\n# Updating antidote plugins"
antidote update

# MAS (macOS only)
if (( $+commands[mas] )); then
    echo "\n# Updating mas apps"
    mas upgrade
fi

# Brew
echo "\n# Updating brew apps"
brew update
brew upgrade --greedy

# nvim
echo "\n# Updating nvim Lazy and Mason"
nvim --headless "+Lazy! sync" "+MasonToolsUpdateSync" "+qa"

# claude code
echo "\n# Updating claude code"
claude update

# pi
echo "\n# Updating pi coding agent and extensions"
pi update --all

# Clean up
echo "\n# Cleaning up"
brew autoremove
brew cleanup -s
brew doctor

# Dump Brewfile
echo "\n# Dumping Brewfile"
mkdir -p $BACKUP_HOME/brew
brew bundle dump --force --file=$BACKUP_HOME/brew/Brewfile
echo "Dumped file to $BACKUP_HOME/brew/Brewfile"

# Importing dock layout (macOS only)
if (( $+commands[defaults] )); then
    echo "\n# Importing saved dock layout from /tmp/dock-layout.plist"
    defaults import com.apple.dock /tmp/dock-layout.plist
    rm -f /tmp/dock-layout.plist
    killall Dock
fi
