#!/bin/zsh

if [[ -z "$VIRTUAL_ENV" ]] ; then
## If .venv folder is found then activate the vitualenv
    if [[ -d ./.venv ]] ; then
        source ./.venv/bin/activate
    fi
else
    echo "No virtual environment found."
fi
