#!/bin/zsh

# Make a brew dump file
echo "\n# Brewfile"
brew bundle dump --force --file=$DOTFILES/brew/Brewfile
echo "Dumped file to $DOTFILES/brew/Brewfile"

# Exporting dock layout
echo "\n# Dock layout"
echo "Exporting dock layout to $DOTFILES/dock/dock-layout.plist"
defaults export com.apple.dock $dotfilDOTFILESes_dir/dock/dock-layout.plist
