#!/bin/zsh

DOTFILES=$HOME/.dotfiles

echo "# Exporting dock layout to /tmp/dock-layout.plist"
defaults export com.apple.dock /tmp/dock-layout.plist

echo "\n# Updating antidote plugins"
antidote update

echo "\n# Updating asdf plugins"
asdf plugin update --all

echo "\n# Updating mas apps"
mas upgrade

echo "\n# Updating brew apps"
brew upgrade --greedy

echo "\n# Cleaning up"
brew autoremove
brew cleanup -s
brew doctor

echo "\n# Dumping Brewfile"
brew bundle dump --force --file=$DOTFILES/brew/Brewfile
echo "Dumped file to $DOTFILES/brew/Brewfile"

echo "\n# Importing saved dock layout from /tmp/dock-layout.plist"
defaults import com.apple.dock /tmp/dock-layout.plist
rm -f /tmp/dock-layout.plist
killall Dock
