#!/bin/zsh

# Uninstall
echo "# Uninstalling $@"
brew uninstall --zap $@

# Clean up
echo "\n# Cleaning up"
brew autoremove
brew cleanup -s
brew doctor

# Dump Brewfile
echo "\n# Dumping Brewfile"
brew bundle dump --force --file=$BACKUP_HOME/brew/Brewfile
echo "Dumped file to $BACKUP_HOME/brew/Brewfile"

# Exporting dock layout
echo "Exporting dock layout to $BACKUP_HOME/dock/dock-layout.plist"
defaults export com.apple.dock $BACKUP_HOME/dock/dock-layout.plist
