#!/bin/zsh

echo "# Uninstalling $@"
brew uninstall --zap $@

echo "\n# Cleaning up"
brew autoremove
brew cleanup -s
brew doctor

echo "\n# Dumping Brewfile"
brew bundle dump --force --file=$DOTFILES/brew/Brewfile
echo "Dumped file to $DOTFILES/brew/Brewfile"

echo "Done"
