#!/bin/zsh

if [ -z "$(ls -A $VIRTUALENV_DIR 2>/dev/null)" ]; then
    echo "No virtual environments found in '$VIRTUALENV_DIR'"
    return 0
fi

echo "Available virtual environments:"
for venv in "$VIRTUALENV_DIR"/*; do
    echo "\t-  $(getvenv $(basename "$venv"))"
done
