#!/bin/zsh

if [ -z "$1" ]; then
    echo "Usage: mkvenv <venv_name>"
    return 1
fi

local venv_path="$VIRTUALENV_DIR/$1"

# Check if the virtual environment already exists
if [ -d "$venv_path" ]; then
    echo "Virtual environment '$(getvenv $1)' already exists"
    return 1
else
    $(asdf which python) -m venv "$venv_path"
    echo "Virtual environment '$(getvenv $1)' created in '$venv_path'"
fi
