#!/bin/zsh

# Set verbose mode for "log" function if it is not set
if [ -z "$_VERBOSE" ]; then
    _VERBOSE=1
fi

if [ -z "$1" ]; then
    echo "Usage: mkvenv <venv_name>"
    return 1
fi

local venv_path="$VIRTUALENV_DIR/$1"

# Check if the virtual environment already exists
if [ -d "$venv_path" ]; then
    log "Virtual environment '$(getvenv $1)' already exists"
    return 1
else
    $(asdf which python) -m venv "$venv_path"
    log "Virtual environment '$(getvenv $1)' created in '$venv_path'"
fi
