#!/bin/zsh

if [ -z "$1" ]; then
    echo "Usage: rmvenv <venv_name>"
    return 1
fi

local venv_path="$VIRTUALENV_DIR/$1"

# Check if the virtual environment already exists
if [ -d "$venv_path" ]; then
    # Get the name of the currently activated environment
    local current_env=$(basename "$VIRTUAL_ENV" 2>/dev/null)

    # Deactivate the environment if activated
    if [[ "$current_env" == "$1" ]]; then
        deactivate
        echo "Virtual environment '$(getvenv $1)' deactivated"
    fi

    echo "Virtual environment '$(getvenv $1)' removed"
    rm -rf "$VIRTUALENV_DIR/$1"
else
    echo "Virtual environment '$1' not found"
    return 1
fi
