#!/bin/zsh

if [ -z "$1" ]; then
    echo "Usage: workon <venv_name>\n"
    lsvenv
    return 1
fi

local venv_path="$VIRTUALENV_DIR/$1"

# Check if the virtual environment exists
if [ -d "$venv_path" ]; then
    source "$venv_path/bin/activate"
    echo "Virtual environment '$(getvenv $1)' activated"
else
    echo "Virtual environment '$1' not found"
    return 1
fi
