#!/usr/bin/env zsh

# Runs the backup script
backup() {
    $DOTFILES/scripts/backup.zsh
}

# Update mas and brew apps and cleanup while keeping the dock layout
brewup() {
    defaults export com.apple.dock /tmp/dock-layout.plist
    mas upgrade
    brew upgrade --greedy
    brew autoremove
    brew cleanup -s
    brew bundle dump --force --file=$DOTFILES/brew/Brewfile
    defaults import com.apple.dock /tmp/dock-layout.plist
    killall Dock
    rm -f /tmp/dock-layout.plist
    brew doctor
}

# Uninstall a brew app (with zap) and cleanup
brewzap() {
    brew uninstall --zap $@
    brew autoremove
    brew cleanup -s
    brew bundle dump --force --file=$DOTFILES/brew/Brewfile
    brew doctor
}

# Run pip with no virtualenv active
gpip() {
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

# Run command assumingno virtualenv is active
# nopip() {
#     PIP_REQUIRE_VIRTUALENV="" "$@"
# }

# Open container volume using docker/nerdctl/podman in busybox shell
# dockervol_sh() {
#     docker run --rm -it -v $1:/data busybox sh
# }
nerdctlvol_sh() {
    nerdctl run --rm -it -v $1:/data busybox sh
}
# podmanvol_sh() {
#     podman run --rm -it -v $1:/data busybox sh
# }

# Copy contents of container volume using docker/nerdctl/podman to vol_$RAND_DIR in current directory
# dockervol_cp() {
#     RAND_DIR=$(cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c8)
#     mkdir $(pwd)/vol_"$RAND_DIR"
#     docker run --rm -it -v $1:/data -v $(pwd)/vol_"$RAND_DIR":/mnt busybox sh -c "cp -r /data/* /mnt"
#     echo ">> Copied contents to '$(pwd)/vol_$RAND_DIR'"
#     echo "$(pwd)/vol_$RAND_DIR" | pbcopy
#     cd "$(pwd)/vol_$RAND_DIR"
#     unset RAND_DIR
# }
nerdctlvol_cp() {
    RAND_DIR=$(cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c8)
    mkdir $(pwd)/vol_"$RAND_DIR"
    nerdctl run --rm -it -v $1:/data -v $(pwd)/vol_"$RAND_DIR":/mnt busybox sh -c "cp -r /data/* /mnt"
    echo ">> Copied contents to '$(pwd)/vol_$RAND_DIR'"
    echo "$(pwd)/vol_$RAND_DIR" | pbcopy
    cd "$(pwd)/vol_$RAND_DIR"
    unset RAND_DIR
}
# podmanvol_cp() {
#     RAND_DIR=$(cat /dev/urandom | base64 | tr -dc '0-9a-zA-Z' | head -c8)
#     mkdir $(pwd)/vol_"$RAND_DIR"
#     podman run --rm -it -v $1:/data -v $(pwd)/vol_"$RAND_DIR":/mnt busybox sh -c "cp -r /data/* /mnt"
#     echo ">> Copied contents to '$(pwd)/vol_$RAND_DIR'"
#     echo "$(pwd)/vol_$RAND_DIR" | pbcopy
#     cd "$(pwd)/vol_$RAND_DIR"
#     unset RAND_DIR
# }
